name: i18n

on:
  push:
    branches-ignore:    
      - staging
      - production

permissions: write-all

jobs:
  i18n:
    runs-on: ubuntu-latest
    steps:
      - uses: knitkode/koine/actions/i18n@main
